title: ssh-easy
description: A simple SSH connection manager with Terminal UI for Linux and Windows
url: "https://waschbaerimhaus.github.io"
baseurl: "/ssh-easy"

author:
  name: Kurt Ingwer

# Kein Jekyll-Theme – eigenes Layout unter _layouts/default.html
# theme: minima

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
